version: '3.8'
services:
  db2:
    container_name: db2
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mc
      MYSQL_DATABASE: AGDev43
      MYSQL_ROOT_HOST: '%'
    ports:
      - "03306:3306"
    # networks:
    #   - my-network
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  phpmyadmin2:
    container_name: phpmyadmin2
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db2
    environment:
      PMA_HOST: db2
      PMA_USER: root
      PMA_PASSWORD: mc
    ports:
      - "8080:80"
    # networks:
    #   - my-network
